### PR TITLE
chore: Response e2e typesafety

### PR DESCRIPTION
**Pull request by Rakemoon**
This pull req containing small change for type safety sake. Youll find it easy when integrating with hono/client.

tbh only the response for now. next ill try integrating type safety for params, query, and body

### CODE REVIEW

**Comment by Rakemoon** [comment]
Uploading 20241019-0954-17.5528820.mp4…

forgot for adding the demo

**Comment by Rakemoon** [comment]
Here the demo

**Comment by Rakemoon** [comment]
Here The demo

image_2024-10-19_171827806

**Comment by RaihanArdianata** [comment]
nice , thanks

**Pull request merged**
